name: Snapshots

on:
  workflow_dispatch:
  push:
    branches: [ main, 'issue/**' ]

permissions: read-all

jobs:
  build-snapshots:
    name: Build and deploy snapshots
    if: ${{ github.repository_owner == 'spring-projects' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@main
        with:
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Setup MongoDB Server
        uses: spring-projects/spring-data-build/actions/setup-mongodb@main
        with:
          replica-set: 'rs0'
      - name: Deploy to Artifactory
        uses: spring-projects/spring-data-build/actions/maven-artifactory-deploy@main
        with:
          build-name: 'spring-data-mongodb'
          username: '${{ secrets.ARTIFACTORY_USERNAME }}'
          password: '${{ secrets.ARTIFACTORY_PASSWORD }}'
